// Textes de l'interface. Aucun texte en dur dans les composants.

import type { Genre } from './partie';

export const TEXTES = {
  titreJeu: 'La bonne passe',
  sousTitre: 'Amsterdam · maison close',
  tourneTelephone: {
    titre: 'Tourne ton téléphone',
    detail: 'La maison se visite en paysage.',
  },
  emplacements: {
    libre: 'Emplacement libre',
    libreDetail: 'Une maison à reprendre, presque vide.',
    illisible: 'Sauvegarde illisible',
    illisibleDetail: 'Cette partie ne peut pas être chargée.',
    nouvellePartie: 'Nouvelle partie',
    continuer: 'Continuer',
    supprimer: 'Supprimer',
    chapitre: (n: number) => `Chapitre ${n}`,
    jour: (n: number) => `Jour ${n}`,
    dernierePartie: 'Dernière partie',
  },
  confirmationSuppression: {
    titre: 'Supprimer cette partie ?',
    detail: (prenom: string, maison: string) =>
      `${prenom} et ${maison} disparaîtront pour de bon. Madame Josée ne gardera même pas les clés.`,
    detailIllisible: 'Cette sauvegarde abîmée sera effacée pour de bon.',
    annuler: 'Annuler',
    confirmer: 'Supprimer',
  },
  dates: {
    jamais: '—',
    instant: 'à l’instant',
    minutes: (n: number) => `il y a ${n} min`,
    heures: (n: number) => `il y a ${n} h`,
    hier: 'hier',
    le: (date: string) => `le ${date}`,
  },
  creation: {
    titre: 'Qui reprend la maison ?',
    tenue: (n: number) => `Tenue ${n}`,
    prenom: 'Ton prénom',
    prenomExemple: 'Anouk, Bram, Inès…',
    maison: 'Nom de la maison',
    apercu: 'L’enseigne, sur la façade',
    retour: 'Retour',
    valider: 'Ouvrir la maison',
    erreurs: {
      prenom: {
        vide: 'Il te faut un prénom pour signer les factures.',
        long: (max: number) => `${max} caractères au maximum.`,
        caracteres: 'Lettres, espaces, apostrophes et traits d’union seulement.',
        injurieux: 'Madame Josée fronce les sourcils. Un autre prénom ?',
      },
      maison: {
        vide: 'Une maison sans nom, c’est une maison sans clients.',
        long: (max: number) => `${max} caractères au maximum, sinon le néon déborde.`,
        caracteres: 'Lettres, chiffres et ponctuation simple seulement.',
        injurieux: 'Le voisinage n’appréciera pas. Trouve un nom plus élégant.',
      },
    },
  },
  jeu: {
    menu: 'Menu',
    bienvenue: (prenom: string, genre: Genre, maison: string) =>
      `Bienvenue, ${prenom}. Te voilà ${accord(genre, 'patronne', 'patron')} ${de(maison)}.`,
    regime: 'Amsterdam · légal',
    ouvert: 'Ouvert',
    ferme: 'Fermé',
    reputation: (n: number) => `★ ${n}`,
    reputationLabel: 'Réputation',
    pause: 'Pause',
    vitesse: (n: number) => `×${n}`,
    vitesseLabel: (n: number) => `Vitesse ×${n}`,
  },
  jours: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
  date: (jourSemaine: string, jour: number) => `${jourSemaine}, jour ${jour}`,
  onglets: {
    maison: 'Maison',
    personnel: 'Personnel',
    clientele: 'Clientèle',
    finances: 'Finances',
    relations: 'Relations',
    journal: 'Journal',
    verrouille: (nom: string, palier: number) => `${nom}, s’ouvre au palier ${palier}`,
  },
  panneau: {
    prochainPalier: 'Prochain palier',
    chambres: 'Chambres',
    piecesCommunes: 'Pièces communes',
    enService: 'En service',
    sousDraps: 'Sous des draps',
    ferme: 'Fermé',
    ouvert: 'Ouvert',
    proprete: 'Propreté',
    etat: 'État',
    premium: 'Premium',
    retour: '‹ Retour',
    renovationVerrouillee: (palier: number, nom: string) =>
      `Rénovation possible au palier ${palier} (${nom}) : 900 € et 8 h de travaux.`,
    barVerrouille: (palier: number, nom: string) => `Le bar rouvre au palier ${palier} (${nom}).`,
    ongletPlusTard: 'Palier atteint : cet onglet arrive dans une prochaine version du jeu.',
    ongletVerrouille: (palier: number, nom: string, objectif: string) =>
      `S’ouvre au palier ${palier}, « ${nom} » : ${objectif.charAt(0).toLowerCase()}${objectif.slice(1)}`,
    recrutementVerrouille: (palier: number, nom: string) => `Recrutement : palier ${palier} (${nom}).`,
    tresorerie: 'Trésorerie',
    emprunt: 'Emprunt de rachat',
    mensualite: 'Prochaine mensualité',
    mensualiteDetail: (montant: string, jour: number, dans: number) =>
      `${montant} au jour ${jour}${dans > 0 ? `, dans ${dans} jour${dans > 1 ? 's' : ''}` : ''}`,
    journalVide: 'Rien à signaler pour l’instant.',
    renover: (prix: string, heures: number) => `Rouvrir la chambre (${prix}, ${heures} h de travaux)`,
    renoverDetail: 'Les ouvriers enlèvent les draps, repeignent et changent la literie.',
    renoverTropCher: (prix: string) => `Il te faut ${prix} en caisse pour lancer les travaux.`,
    travaux: 'Travaux en cours',
    travauxFin: (heure: string) => `Les ouvriers s’activent. Réouverture prévue à ${heure}.`,
    equipeMenage: 'Équipe de ménage',
    effectifMenage: (n: number, salaire: string) =>
      `${n} personne${n > 1 ? 's' : ''} · ${salaire} par jour et par personne`,
    ajouterMenage: 'Embaucher',
    retirerMenage: 'Se séparer',
    menageVerrouille: (palier: number, nom: string) => `Deuxième personne au ménage : palier ${palier} (${nom}).`,
    recrutementOuvert: 'Des candidats vont se présenter dans la journée. Garde l’œil sur la porte.',
    reserve: 'Réserve de sécurité',
    reserveDetail: 'Mise de côté à chaque fermeture. Elle paie la mensualité en premier.',
    reserveMontant: 'En réserve',
    reserveTaux: (pourcent: number) => `${pourcent} %`,
    reserveTauxLabel: (pourcent: number) => `Mettre ${pourcent} % de la recette du soir de côté`,
    retirerReserve: (montant: string) => `Reprendre la réserve (${montant})`,
    reserveVerrouillee: (palier: number, nom: string) => `Réserve de sécurité : palier ${palier} (${nom}).`,
    empruntRestant: (restantes: number) => `${restantes} mensualité${restantes > 1 ? 's' : ''} restante${restantes > 1 ? 's' : ''}`,
    empruntRembourse: 'Remboursé. La banque t’envoie des fleurs.',
  },
  clientele: {
    reputation: (n: number) => `Réputation ★ ${n}`,
    reputationDetail: 'La moyenne des satisfactions de chaque segment. Les habitués comptent un peu plus que les autres.',
    segments: 'Segments',
    satisfaction: 'Satisfaction',
    ecart: (delta: number) => (Math.abs(delta) < 0.5 ? 'stable' : `${delta > 0 ? '+' : '−'}${Math.abs(delta).toFixed(1).replace('.', ',')}`),
    ecartDetail: 'Écart depuis la dernière ouverture',
    frequentation: (recus: number, repartis: number) => `${recus} reçus · ${repartis} repartis`,
    frequentationDetail: (nuits: number) => `clients ${nuits > 1 ? `des ${nuits} dernières nuits` : 'de la dernière nuit'}.`,
    aucuneNuit: 'Pas encore de nuit à compter.',
    budget: 'Budget',
    budgetDetail: (min: string, max: string) => `De ${min} à ${max} par rendez-vous, selon la qualité.`,
    attend: 'Ce qu’ils attendent',
    talents: (liste: string) => `Talents recherchés : ${liste}.`,
    sensible: 'Ce qui les fâche',
    attire: 'Ce qui les attire',
    offreAttire: (offre: string) => `${offre} les attire.`,
    rienDeSpecial: 'Rien de particulier : une maison bien tenue, et c’est déjà beaucoup.',
    patience: (minutes: number) => `Patience sur le quai : ${minutes} min environ.`,
    regles: 'Règles de la maison',
    reglesResume: (tarif: string, formule: string, selection: string, priorite: string) =>
      `Tarif ${tarif.toLowerCase()} · ${formule.toLowerCase()} · sélection ${selection.toLowerCase()} · ${priorite.toLowerCase()}`,
    reglesAide: 'Elles s’appliquent tout de suite, même en pleine soirée.',
    tarif: 'Tarif général',
    formule: 'Formule',
    selection: 'Sélection à l’entrée',
    priorite: 'Priorité d’accueil',
    visibilite: 'Visibilité',
    aVenir: 'À venir',
    aVenirDetail: (palier: number) => `palier ${palier}`,
  },
  nouveautes: {
    titre: 'Du nouveau dans la maison',
    intro: 'Ta partie a déjà passé ces paliers. Voici ce qui s’y ajoute :',
    ok: 'Voyons ça',
  },
  palierCarte: {
    titre: (numero: number, nom: string) => `Palier ${numero} : ${nom}`,
    ouvre: 'Nouveau palier atteint. Voici ce qui s’ouvre :',
    suivant: (numero: number, nom: string, objectif: string) =>
      `Prochain palier, ${numero}. ${nom} : ${objectif.charAt(0).toLowerCase()}${objectif.slice(1)}`,
    ok: 'Parfait',
  },
  journal: {
    ouverture: (maison: string) => `${maison} ouvre ses portes. Le néon s’allume.`,
    fermeture: 'Fermeture. Les rideaux retombent, la maison dort.',
    nouveauJour: (jourSemaine: string, jour: number) => `${jourSemaine}, jour ${jour}. La journée commence.`,
    briefing: 'Briefing de 19 h : la soirée se prépare.',
    arrivee: (client: string) => `${client} attend sur le quai.`,
    clientParti: (client: string) => `${client} en a eu assez d’attendre sur le quai.`,
    filePleine: 'Le quai est plein : un client passe son chemin.',
    refuse: (client: string, feminin: boolean) =>
      `${client} est refusé${feminin ? 'e' : ''} à la porte. ${feminin ? 'Elle' : 'Il'} repart en maugréant.`,
    portier: (montant: string) => `Le portier prend son poste, costume noir et oreillette : ${montant}.`,
    tarif: (nom: string) => `Nouveau tarif : ${nom}.`,
    formule: (nom: string) => `Nouvelle formule : ${nom.charAt(0).toLowerCase()}${nom.slice(1)}.`,
    selection: (nom: string) => `Sélection à l’entrée : ${nom.toLowerCase()}.`,
    priorite: (nom: string) => `Priorité d’accueil : ${nom.charAt(0).toLowerCase()}${nom.slice(1)}.`,
    visibilite: (nom: string) => `Visibilité : ${nom.charAt(0).toLowerCase()}${nom.slice(1)}.`,
    visibiliteCout: (montant: string) => `La maison se fait connaître ce soir : ${montant}.`,
    debutRdv: (employe: string, client: string, dansChambre: string) =>
      `${employe} reçoit ${client.charAt(0).toLowerCase()}${client.slice(1)} ${dansChambre}. Les rideaux se ferment.`,
    finRdv: (client: string, avis: string, montant: string) => `${client} : « ${avis} » (+${montant})`,
    salaires: (montant: string) => `Midi : salaires des équipes, ${montant}.`,
    debutTravauxBar: (montant: string, heure: string) => `Les ouvriers ôtent les draps du bar (${montant}). Fin prévue à ${heure}.`,
    finTravauxBar: 'Le bar rouvre ! Josée a retrouvé quelques bouteilles à la cave.',
    equipeBar: (n: number) => (n === 0 ? 'Plus personne derrière le comptoir.' : `Équipe Bar : ${n} personne${n > 1 ? 's' : ''}.`),
    livraisonBar: (montant: string) => `Livraison express de bouteilles pour le bar : ${montant}.`,
    barVide: 'Le bar est à sec. Les groupes regardent leurs verres vides.',
    theme: (annonce: string, montant: string) => `${annonce} (${montant})`,
    bilanSemaine: (numero: number, resultat: string) => `Lundi : bilan de la semaine ${numero}, ${resultat}.`,
    tendance: (nom: string) => `Cette semaine en ville : ${nom.charAt(0).toLowerCase()}${nom.slice(1)}.`,
    grossiste: 'Le grossiste passe au bureau, catalogue sous le bras.',
    avanceAcceptee: (montant: string, jour: string) => `Avance du grossiste acceptée : ${montant} à rembourser ${jour}.`,
    avanceRefusee: 'Le grossiste repart avec son catalogue.',
    remboursementAvance: (montant: string) => `Remboursement de l’avance au grossiste : ${montant}.`,
    charges: (montant: string) => `Lundi : charges fixes (énergie, assurance, licence), ${montant}.`,
    dispute: 'Ça chauffe sur le quai : deux clients se disputent la file.',
    disputeDegeneree: (montant: string) => `La dispute a dégénéré : un fauteuil en moins (${montant}) et des voisins fâchés.`,
    disputeVerre: 'Deux verres offerts ont ramené la paix sur le quai.',
    disputeCalmee: (prenom: string) => `${prenom} a calmé le jeu avec autorité.`,
    disputeRatee: 'Tu as calmé le jeu… en prenant un parapluie dans l’épaule.',
    nettoyage: (deChambre: string, montant: string) => `Nettoyage express ${deChambre} (${montant}).`,
    livraisonLinge: (montant: string) => `Livraison express : 50 draps propres (${montant}).`,
    repos: (prenom: string) => `${prenom} se repose pour le reste de la nuit.`,
    palier: (numero: number, nom: string) => `Palier ${numero} atteint : ${nom}.`,
    debutTravaux: (deChambre: string, montant: string, heure: string) =>
      `Travaux ${deChambre} (${montant}). Fin prévue à ${heure}.`,
    finTravaux: (chambre: string) => `${chambre} est rouverte. Ça sent la peinture fraîche.`,
    miseEnReserve: (montant: string) => `${montant} mis de côté dans la réserve.`,
    tauxReserve: (pourcent: number) => `Réserve de sécurité : ${pourcent} % de la recette du soir.`,
    retraitReserve: (montant: string, remarque: string) => `Réserve reprise : ${montant}. Josée : « ${remarque} »`,
    mensualite: (montant: string, depuisReserve: string) =>
      `La banque prélève la mensualité : ${montant}, dont ${depuisReserve} pris sur la réserve.`,
    equipeMenage: (n: number) => `L’équipe de ménage compte désormais ${n} personne${n > 1 ? 's' : ''}.`,
    visite: (prenom: string) => `${prenom} frappe à la porte pour un entretien.`,
    marche: (n: number) => `Lundi : ${n} candidature${n > 1 ? 's' : ''} sur le bureau.`,
    candidatParti: (prenom: string) => `${prenom} a fini par dire oui à une autre maison.`,
    contreOffre: (prenom: string, pourcent: number) => `${prenom} fait une contre-proposition : ${pourcent} %.`,
    candidatVexe: (prenom: string) => `${prenom} remet sa veste : « Bonne chance pour la suite. »`,
    candidatRefuse: (prenom: string) => `Tu as poliment refusé ${prenom}.`,
    reflexion: (prenom: string) => `${prenom} attend ta réponse.`,
    embauche: (prenom: string, pourcent: number) => `${prenom} rejoint la maison à ${pourcent} %. Période d’essai d’une semaine.`,
    finEssai: (prenom: string) => `Fin de la période d’essai de ${prenom} : à toi de décider.`,
    essaiConfirme: (prenom: string) => `${prenom} reste dans la maison. Sanne a déjà prévu un gâteau.`,
    finCollaboration: (prenom: string) => `${prenom} rend ses clés. Sans rancune, promis.`,
    traitRevele: (prenom: string, trait: string) => `On découvre ${prenom} sous un nouveau jour : ${trait.toLowerCase()}.`,
    menaceDepart: (prenom: string, jour: string, genre: 'f' | 'm') =>
      `${prenom} parle de partir. Il te reste jusqu’à ${jour} pour ${genre === 'f' ? 'la' : 'le'} retenir.`,
    menaceLevee: (prenom: string) => `${prenom} a retrouvé le sourire : plus question de partir.`,
    depart: (prenom: string) => `${prenom} a rendu ses clés. La loge paraît plus grande, et plus triste.`,
    promesseRompue: (prenom: string, genre: 'f' | 'm') =>
      `${prenom} attend toujours la soirée de repos promise. ${genre === 'f' ? 'Elle' : 'Il'} ne l’oubliera pas.`,
    entretienEcouter: (prenom: string) => `Tu as écouté ${prenom}. Ça ne coûte rien, et ça compte.`,
    entretienPromettre: (prenom: string) => `Tu as promis une soirée de repos à ${prenom}, sous 3 jours.`,
    entretienRecadrer: (prenom: string) => `Tu as recadré ${prenom}. Concentration maximale ce soir, sourire minimal.`,
    prime: (prenom: string, montant: string) => `Prime de ${montant} pour ${prenom}.`,
    amitie: (a: string, b: string) => `${a} et ${b} sont désormais inséparables.`,
    rivalite: (a: string, b: string) => `Entre ${a} et ${b}, le courant ne passe plus.`,
    imprevu: (titre: string) => `Imprévu : ${titre.charAt(0).toLowerCase()}${titre.slice(1)}.`,
    intrigue: (titre: string) => `${titre}.`,
    candidatVedette: (prenom: string) => `${prenom} attend au salon pour un entretien : sa candidature est dans l’onglet Personnel.`,
    defi: (titre: string) => `Défi de la semaine : ${titre.charAt(0).toLowerCase()}${titre.slice(1)}.`,
    defiConclu: (titre: string, reussi: boolean) => (reussi ? `Défi réussi : ${titre.charAt(0).toLowerCase()}${titre.slice(1)}.` : `Défi manqué : ${titre.charAt(0).toLowerCase()}${titre.slice(1)}.`),
    bilanMois: (numero: number, reussi: boolean) => `Fin du mois ${numero} : objectif ${reussi ? 'atteint' : 'manqué'}.`,
    remboursement: (prenom: string, montant: string) => `${prenom} te rend les ${montant} que tu lui avais avancés.`,
  },
  recrutement: {
    candidats: 'Candidats',
    aucunCandidat: 'Personne en attente. Le marché se renouvelle chaque lundi.',
    effectif: (n: number, max: number) => `Équipe : ${n} sur ${max}`,
    recevoir: 'Recevoir',
    source: {
      visite: 'Visite à la maison',
      annonce: 'Petite annonce',
      boucheAOreille: 'Bouche-à-oreille',
      debauchage: 'De chez le Chat Noir',
    },
    attendJusquA: (jour: string) => `Attend ta réponse jusqu’à ${jour}`,
    titreCandidate: 'Une candidate',
    titreCandidat: 'Un candidat',
    uneQuestion: 'Une question avant de décider',
    traitRevele: 'Trait révélé :',
    proposition: 'Ta proposition',
    propositionAvantQuestion: 'Pose d’abord ta question.',
    proposer: (pourcent: number) => `${pourcent} %`,
    proposerLabel: (pourcent: number) => `Embaucher à ${pourcent} %`,
    detailsParts: 'La part que la recrue garde sur chaque rendez-vous. Au-dessus de 50 %, loyauté en hausse.',
    contreOffre: (prenom: string, pourcent: number) => `${prenom} demande ${pourcent} %. Accepter, ou insister plus bas ?`,
    accepterContre: (pourcent: number) => `Accepter ${pourcent} %`,
    reflechir: 'Réfléchir',
    refuser: 'Refuser poliment',
    complet: (max: number) => `La maison ne peut pas accueillir plus de ${max} personnes pour l’instant.`,
  },
  planning: {
    titre: 'Planning du soir',
    travaille: 'Travaille',
    repos: 'Repos',
    reposDetail: 'Repos : fatigue en baisse, moral en hausse.',
    unAuMoins: 'Il faut au moins une personne en service.',
    rdvMax: 'Rendez-vous max par personne',
    rdvMaxAide: ['Personnel reposé, recettes limitées.', 'Raisonnable.', 'Rentable… jusqu’à l’épuisement.'],
    charge: (formule: string, charge: number) => `${formule} : chacun compte pour ${String(charge).replace('.', ',')}.`,
    promesse: 'repos promis',
    menace: 'veut partir',
  },
  suivi: {
    entretien: 'Entretien individuel',
    entretienFait: 'Entretien déjà fait aujourd’hui',
    entretienOccupe: 'En rendez-vous',
    primes: 'Prime',
    prime: (montant: string) => `Prime de ${montant}`,
    primeAttente: (jours: number) => `Prochaine prime possible dans ${jours} jour${jours > 1 ? 's' : ''}`,
    menace: (jour: string) => `Veut partir. Il te reste jusqu’à ${jour} pour remonter son moral au-dessus de 30.`,
    promesse: (jour: string) => `Repos promis : à placer au planning avant ${jour}.`,
    affinites: 'Affinités',
    niveauxAffinite: (v: number) =>
      v >= 40 ? 'Amitié' : v >= 15 ? 'Complicité' : v > -15 ? 'Neutre' : v > -30 ? 'Froid' : 'Rivalité',
    titreEntretien: (prenom: string) => `Entretien avec ${prenom}`,
    fermer: 'Plus tard',
  },
  intrigue: {
    /** Étiquette au-dessus du titre de la carte. */
    etiquette: (titre: string) => `Intrigue · ${titre}`,
    /** Étiquette des événements du quartier (v0.5). */
    quartier: 'Le quartier',
    tropCher: 'Trésorerie insuffisante',
    continuer: 'Continuer',
    denouement: 'Dénouement',
    enCours: 'Intrigues en cours',
  },
  voisinage: {
    titre: 'Voisinage',
    /** Calme, agacé (au-dessus du seuil de récidive), excédé (au-dessus du seuil de plainte). */
    niveaux: ['Calme', 'Agacé : on entend des soupirs', 'Excédé : les fenêtres claquent'],
    insonorise: 'salon insonorisé',
  },
  imprevu: {
    reussite: 'C’est passé.',
    echec: 'Raté.',
  },
  aide: {
    titre: 'Aide',
    bouton: '?',
    ok: 'Compris',
  },
  adieu: {
    titre: (prenom: string) => `${prenom} s’en va`,
    texte: (prenom: string) =>
      `${prenom} a vidé son casier et laissé un mot sur le miroir de la loge. Le reste de l’équipe accuse le coup, et quelques habitués demandent déjà de ses nouvelles.`,
    ok: 'Tourner la page',
  },
  essai: {
    titre: (prenom: string) => `Fin d’essai : ${prenom}`,
    texte: (prenom: string, nuits: number) =>
      `Une semaine déjà. ${prenom} a travaillé ${nuits} nuit${nuits > 1 ? 's' : ''} dans la maison. On continue ensemble ?`,
    garder: 'Garder dans l’équipe',
    garderDetail: 'Moral et loyauté ne bougent pas : la confiance s’installe.',
    separer: 'Se séparer',
    separerDetail: 'Pendant l’essai, sans conséquence pour le reste de l’équipe.',
    occupe: 'En rendez-vous : attends la fin pour te séparer.',
  },
  scene: {
    occupe: '♥ Occupé',
    chambreFermee: (nom: string) => `${nom} : fermée`,
    travaux: (heure: string) => `Travaux · fin à ${heure}`,
    pieceFermee: (nom: string) => `${nom} : fermé`,
    ceSoir: 'CE SOIR',
  },
  briefing: {
    tendances: 'Cette semaine en ville :',
    theme: 'Soirée à thème',
    sansTheme: 'Pas de thème',
    sansThemeDetail: 'Une soirée comme les autres. Gratuit.',
    themePrix: (prix: string) => `${prix}, payés maintenant`,
    themeLasse: (pourcent: number) => `Déjà vu cette semaine : effet réduit à ${pourcent} %.`,
    themeTropCher: 'Pas assez en caisse.',
    regles: 'Règles de la maison (onglet Clientèle) :',
    titre: 'Briefing de 19 h',
    ceSoir: 'Qui travaille ce soir ?',
    horaires: (ouverture: string, fermeture: string) => `Ouverture à ${ouverture}, fermeture à ${fermeture}.`,
    chambresEnService: (n: number, total: number) => `${n} chambre${n > 1 ? 's' : ''} en service sur ${total}`,
    planningVerrouille: (prenom: string) => `Le planning s’ouvre au palier 1. Ce soir, ${prenom} est seule.`,
    linge: 'Linge propre',
    stockLinge: (n: number) => `Stock : ${n} draps`,
    commanderLinge: (draps: number, prix: string) => `Commander ${draps} draps (${prix}), livrés à l’ouverture`,
    bar: 'Bar',
    stockBar: (n: number) => `Stock : ${n} bouteilles`,
    commanderBar: (bouteilles: number, prix: string) => `Commander ${bouteilles} bouteilles (${prix}), livrées à l’ouverture`,
    barSansEquipe: 'Personne derrière le comptoir : le bar ne sert pas ce soir.',
    offre: 'L’offre du soir',
    conseilPremierSoir: 'Garde un œil sur le Boudoir : c’est ta seule chambre. Et Sanne, ta seule hôtesse.',
    lancer: 'Lancer la soirée',
  },
  bilan: {
    titre: (numero: number) => `Fin de la nuit ${numero}`,
    recettes: 'Recettes',
    totalRecettes: 'Total des recettes',
    depenses: 'Dépenses',
    totalDepenses: 'Total des dépenses',
    postesRecettes: {
      rendezVous: (clients: number) => `Rendez-vous (${clients} client${clients > 1 ? 's' : ''})`,
      bar: 'Bar',
      autres: 'Autres (imprévus, pourboires…)',
      assurance: 'Remboursé par l’assurance',
    },
    postesDepenses: {
      partPersonnel: (pourcentage: number) => `Part du personnel (${pourcentage} %)`,
      salaires: 'Salaires de la journée (payés à midi)',
      charges: 'Charges fixes',
      linge: 'Linge',
      bar: 'Réassort du bar',
      express: 'Livraisons express',
      travaux: 'Travaux',
      menage: 'Nettoyages express',
      personnel: 'Primes et avances',
      portier: 'Portier',
      visibilite: 'Visibilité',
      themes: 'Thème de la soirée',
      relations: 'Relations',
      assurance: 'Assurance',
      incidents: 'Incidents',
      mensualite: 'Mensualité',
      avance: 'Remboursement du grossiste',
    },
    gagne: 'Gagné cette nuit',
    dontReserve: 'dont mis en réserve',
    retraitReserve: 'Retiré de la réserve',
    tresorerie: 'Trésorerie',
    servis: 'Clients reçus',
    perdus: 'Clients perdus',
    reputation: 'Réputation',
    meilleurAvis: 'Meilleur avis',
    pireAvis: 'Avis le plus dur',
    fatigue: 'Fatigue en fin de nuit',
    clientele: 'Satisfaction de la nuit',
    theme: 'Thème',
    conseilPerdus: 'Plus de clients perdus que reçus. Il te faudra plus de bras et plus de chambres.',
    conseilBon: 'Belle nuit. Ne t’endors pas sur tes lauriers : le Pink Palace, lui, ne dort jamais.',
    conseilMoyen: 'Correct. On peut faire mieux, et on fera mieux.',
    continuer: 'Continuer',
  },
  disputeCarte: {
    titre: 'Dispute sur le quai',
    texte: 'Deux clients se disputent la place dans la file. Le ton monte, les voisins ouvrent leurs fenêtres.',
    verre: (prix: string) => `Offrir un verre aux deux (${prix})`,
    verreDetail: 'Tout le monde se calme.',
    calmer: 'Descendre calmer le jeu',
    calmerDetail: 'Gratuit, mais ça peut mal tourner.',
    plusTard: 'Laisser faire pour l’instant',
  },
  objectifs: {
    defi: 'Défi de la semaine',
    progression: (valeur: string, cible: string, auPlus: boolean) => (auPlus ? `${valeur} (au plus ${cible})` : `${valeur} sur ${cible}`),
    recompense: (texte: string) => `À la clé : ${texte.charAt(0).toLowerCase()}${texte.slice(1)}.`,
    mois: (numero: number) => `Objectif du mois ${numero}`,
    jugeLe: (jour: number) => `Jugé le jour ${jour}, avec la mensualité.`,
    enBonneVoie: 'En bonne voie',
    reussi: 'Réussi',
    rate: 'Raté',
    defiPasse: 'Le défi de la semaine passée',
    nouveauDefi: 'Le défi de cette semaine',
  },
  bilanMois: {
    titre: (numero: number) => `Fin du mois ${numero}`,
    mensualite: 'Mensualité',
    depuisReserve: (montant: string) => `dont ${montant} pris dans la réserve`,
    avoir: 'Trésorerie et réserve après la mensualité',
    lettre: (maison: string) =>
      `Une lettre de la banque, adressée à ${maison} : la mensualité est passée à découvert. Pour l’instant, un simple rappel à l’ordre.`,
    objectif: 'L’objectif du mois',
    atteint: (valeur: string, cible: string) => `${valeur}, pour ${cible} visés`,
    recompense: 'Réputation en hausse, et l’équipe fête ça.',
    prochain: 'Le mois qui commence',
    continuer: 'Au travail',
  },
  alerteCarte: {
    restant: (minutes: number) => `Encore ${minutes} minutes de jeu avant qu’il soit trop tard.`,
    plusTard: 'Plus tard',
  },
  alertes: {
    chambreSale: (chambre: string) => `${chambre} : chambre sale`,
    linge: 'Plus de linge propre',
    epuisement: (prenom: string, genre: 'f' | 'm') => `${prenom} est ${genre === 'f' ? 'épuisée' : 'épuisé'}`,
    dispute: 'Dispute sur le quai',
    menace: (prenom: string) => `${prenom} veut partir`,
    barVide: (stock: number) => (stock <= 0 ? 'Le bar est vide' : 'Le bar est presque vide'),
  },
  bar: {
    renover: (prix: string, heures: number) => `Rouvrir le bar (${prix}, ${heures} h de travaux)`,
    renoverDetail: 'On retire les draps, on astique le comptoir, on rebranche la tireuse.',
    renoverTropCher: (prix: string) => `Il te faut ${prix} en caisse pour lancer les travaux.`,
    travaux: (heure: string) => `Travaux en cours. Réouverture prévue à ${heure}.`,
    ouvert: 'Ouvert',
    sert: 'Le bar sert',
    vide: 'Le bar est vide',
    sansEquipe: 'Personne au comptoir',
    stock: 'Stock',
    bouteilles: (n: number) => `${n} bouteille${n > 1 ? 's' : ''}`,
    equipe: 'Équipe Bar',
    effectif: (n: number, salaire: string) => (n === 0 ? `Personne · ${salaire} par jour et par personne` : `${n} personne${n > 1 ? 's' : ''} · ${salaire} par jour et par personne`),
    embaucher: 'Embaucher',
    separer: 'Se séparer',
    equipeAide: 'Une personne suffit pour servir. La deuxième rend le service plus agréable.',
    livraison: (bouteilles: number, prix: string) => `Livraison express : ${bouteilles} bouteilles (${prix})`,
    recette: 'Recette de la dernière nuit',
    recetteDetail: 'Chaque client reçu passe au bar : les groupes boivent le plus, les habitués le moins.',
    avance: 'Avance du grossiste',
    avanceDetail: (montant: string, jour: number) => `${montant} à rembourser au jour ${jour}.`,
  },
  semaine: {
    titre: (numero: number) => `Bilan de la semaine ${numero}`,
    recettes: 'Recettes',
    depenses: 'Dépenses',
    resultat: 'Résultat de la semaine',
    postesRecettes: { rendezVous: 'Rendez-vous', bar: 'Bar', autres: 'Divers', assurance: 'Remboursements de l’assurance' },
    postesDepenses: {
      partPersonnel: 'Part du personnel',
      salaires: 'Salaires des équipes',
      charges: 'Charges fixes',
      linge: 'Linge',
      bar: 'Stock du bar',
      express: 'Livraisons express',
      travaux: 'Travaux',
      menage: 'Nettoyages express',
      personnel: 'Primes',
      portier: 'Portier',
      visibilite: 'Visibilité',
      themes: 'Soirées à thème',
      relations: 'Relations avec le quartier',
      assurance: 'Assurance',
      incidents: 'Casse et imprévus',
      mensualite: 'Mensualité',
      avance: 'Remboursement du grossiste',
    },
    reputation: 'Réputation',
    reputationDetail: (debut: number, fin: number) => `★ ${debut} → ★ ${fin}`,
    clients: (recus: number, perdus: number) => `${recus} clients reçus, ${perdus} perdus`,
    satisfaction: 'Satisfaction par segment',
    projection: 'Trésorerie et réserve projetées',
    projectionDetail: 'Si la semaine prochaine ressemble à celle-ci, travaux à part, mensualités et remboursements compris.',
    finSemaine: (n: number) => `Dans ${n} semaine${n > 1 ? 's' : ''}`,
    maintenant: 'Aujourd’hui',
    tendances: 'Cette semaine en ville',
    aucuneTendance: 'Rien de particulier en ville cette semaine.',
    premieresTendances:
      'Nouveau : chaque lundi, je te dirai ce qui se passe en ville. Un congrès, un match, une grève : la clientèle change, à toi d’adapter l’offre. Et au briefing, tu peux désormais programmer une soirée à thème.',
    joseeResultat: (positif: boolean) =>
      positif ? 'Une semaine dans le vert. La banque dormira tranquille, toi aussi.' : 'Une semaine dans le rouge. On serre les boulons, et on regarde où ça fuit.',
    joseeProjection: 'Attention : à ce rythme, la caisse passe sous zéro dans les semaines qui viennent.',
    continuer: 'Au travail',
    revoir: 'Revoir le bilan du lundi',
    enCours: 'Semaine en cours',
    enCoursDetail: (recettes: string, depenses: string) => `Recettes ${recettes} · dépenses ${depenses}`,
  },
  grossiste: {
    titre: 'Le grossiste frappe à la porte',
    intro: (bouteilles: number, valeur: string) =>
      `Monsieur Van Dijk, grossiste en boissons du quartier, a vu ton bar rouvrir. Il te propose ${bouteilles} bouteilles, d’une valeur de ${valeur}, sans rien payer aujourd’hui.`,
    conditions: (montant: string, jours: number) => `Tu rembourses ${montant} dans ${jours} jours, intérêts compris.`,
    josee: 'Du stock sans sortir un sou, c’est tentant. Mais dans deux semaines, il faudra les avoir, ces sous. Et Van Dijk ne fait pas crédit deux fois.',
    accepter: 'Accepter',
    refuser: 'Refuser',
  },
  personnel: {
    ans: (age: number) => `${age} ans`,
    part: (pourcent: number) => `Garde ${pourcent} % de chaque rendez-vous`,
    talents: 'Talents',
    traits: 'Traits',
    ambition: 'Ambition',
    reve: (ambition: string) => `Son rêve : ${ambition.charAt(0).toLowerCase()}${ambition.slice(1)}.`,
    fatigue: 'Fatigue',
    moral: 'Moral',
    loyaute: 'Loyauté',
    rdvCeSoir: (n: number, charge: number, max: number) =>
      Math.abs(charge - n) < 0.01
        ? `Rendez-vous ce soir : ${n} sur ${max}`
        : `Rendez-vous ce soir : ${n}, qui en valent ${charge.toFixed(2).replace(/\.?0+$/, '').replace('.', ',')} sur ${max}`,
    statuts: {
      rdv: 'En rendez-vous',
      repos: 'Au repos ce soir',
      epuisee: (genre: 'f' | 'm') => (genre === 'f' ? 'Épuisée' : 'Épuisé'),
      quota: 'Quota atteint',
      disponible: 'Disponible',
      horsService: 'Hors service',
    },
    enEssai: (jour: string) => `En période d’essai jusqu’à ${jour}`,
    traitCache: 'Trait encore inconnu',
    traitCacheDetail: 'Il se révélera après quelques nuits de travail.',
    mettreAuRepos: 'Repos pour le reste de la nuit',
  },
  actions: {
    nettoyageExpress: (prix: string) => `Nettoyage express (${prix})`,
    livraisonLinge: (draps: number, prix: string) => `Livraison express : ${draps} draps (${prix})`,
    occupee: 'Occupée',
    inutilisable: 'Trop sale pour recevoir : la chambre est bloquée.',
    lingeStock: (n: number) => `${n} draps propres`,
  },
} as const;

/** Accorde un mot selon l'avatar choisi : « patronne » ou « patron ». */
export function accord(genre: Genre, feminin: string, masculin: string): string {
  return genre === 'patronne' ? feminin : masculin;
}

/** « de » devant un nom propre, avec contraction : « du Velours », « des Tulipes », « de La bonne passe ». */
export function de(nom: string): string {
  if (/^le\s/i.test(nom)) return `du ${nom.slice(3)}`;
  if (/^les\s/i.test(nom)) return `des ${nom.slice(4)}`;
  return /^[aeiouyhéèêâîôû]/i.test(nom) ? `d’${nom}` : `de ${nom}`;
}
